# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'PhilosophyNotificationApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PhilosophyNotificationApp

  target 'PhilosophyNotificationAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PhilosophyNotificationAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

  pod 'Firebase/Core'
  pod 'Firebase/Auth'

end
